---
title: "csomap affinity mouse liver lobules"
author: "Dean de Haas"
date: "26-5-2021"
output: html_document
---

```{r setup, include=FALSE}
library('dplyr')
library('reshape2')
library(ggplot2)
```

import datasets

```{r cars}

original_cell_names <- read.table("~/reproduce_liver_analysis/cell_names.txt", quote="\"", comment.char="")
liver_lobules_assigned_layers_to_cells <- read.csv("C:/Users/deand/OneDrive/Documents/Table_S1_completed/liver_lobules_assigned_layers_to_cells.txt", sep=";",row.names = 1)

cells_with_assigned_layers<-data.frame(row.names(liver_lobules_assigned_layers_to_cells),liver_lobules_assigned_layers_to_cells$layer)
colnames(cells_with_assigned_layers)[1]<-'cells'
colnames(cells_with_assigned_layers)[2]<-'layer'


CSOmap_affinity_matrix <- read.csv2("~/CSOmap_affinity_matrix_mouselb.txt", header=FALSE)
colnames(CSOmap_affinity_matrix)<-original_cell_names$V1
rownames(CSOmap_affinity_matrix)<-original_cell_names$V1


```

calculate correlation between the affinity and cellular distances

```{r pressure, echo=FALSE}
original_distances<-as.numeric(as.CSOmap_affinity_matrixrix(dist(liver_lobules_assigned_layers_to_cells,'euclidean')))
CSOmap_affinities<-as.numeric(as.CSOmap_affinity_matrixrix(CSOmap_affinity_matrix))


combined_distances<-data.frame(original_distances,CSOmap_affinities)
table(combined_distances$bin)


bin_mean <-aggregate(combined_distances$CSOmap_affinities, list(combined_distances$original_distances), function(x) mean = mean(x)) 
bin_sd <-aggregate(combined_distances$CSOmap_affinities, list(combined_distances$original_distances), function(x) sd = sd(x))


df<-data.frame(bin_mean,bin_sd$x)
ggplot(df,aes(Group.1,x))+geom_point(size=2)+geom_errorbar(aes(ymin=as.numeric(x)-as.numeric(bin_sd.x),ymax=as.numeric(x)+as.numeric(bin_sd.x)), width=0.2,position=position_dodge(.9)) +xlab("Distance between cells (in layers)") + ylab("Pairwise affinities")+theme(text = element_text(size = 15))+geom_line(size=0.1)#+scale_x_discrete(breaks=c(seq(0,4000,500)))



```
