---
title: "csomap affinity mouse cortex"
author: "Dean de Haas"
date: "26-5-2021"
output: html_document
---

```{r setup, include=FALSE}
library('dplyr')
library('reshape2')
library(ggplot2)
```

import datasets

```{r cars}
#import original positions of the cells
original_positions <- read.csv("~/stitsch_file.txt", row.names=1, sep="")
colnames(original_positions)<-c('ID','X_revised','Y_revised')

#import affinity matrix
CSOmap_affinity_matrix <- read.csv("~/CSOmap_affinity_matrix_mousy_seqfish.txt", header=FALSE)

```

calculate affinity

```{r pressure, echo=FALSE}

distances_original_positions <-as.numeric(as.CSOmap_affinity_matrixrix(dist(original_positions[,c(2,3)],'euclidean')))

CSOmap_affinity<-as.numeric(as.CSOmap_affinity_matrixrix(CSOmap_affinity_matrix))

combined_distances<-data.frame(distances_original_positions,CSOmap_affinity)

combined_distances$bin<-cut(combined_distances$distances_original_positions,c(0,500,1000,1500,2000,2500,3000,3500.4000,4500,5000,5500,6000,6500,7000,7500,8000,8500,9000,9500,Inf))
table(combined_distances$bin)

bin_mean <-aggregate(combined_distances$CSOmap_affinity, list(combined_distances$bin), function(x) mean = mean(x)) 
cor.test(combined_distances$distances_original_positions,combined_distances$CSOmap_affinity,method='spearman')
bin_sd <-aggregate(combined_distances$CSOmap_affinity, list(combined_distances$bin), function(x) sd = sd(x))
df<-data.frame(bin_mean,bin_sd$x)

df$Euclidean_distance<-c(seq(500,9500,500))
my_y_title <- expression(paste("CSOmap's assumption: ", italic("affinity")))
ggplot(df,aes(Euclidean_distance,x))+geom_point(size=3)+ggtitle(my_y_title)+geom_errorbar(aes(ymin=as.numeric(x)-as.numeric(bin_sd.x),ymax=as.numeric(x)+as.numeric(bin_sd.x)), width=100,position=position_dodge(.9)) +xlab("Reference spatial Euclidean distance") + ylab("Pairwise affinities")+theme(text = element_text(size = 15),axis.text.x = element_text( size=15),axis.text.y = element_text( size=15))+geom_line(size=0.1)+scale_x_continuous(breaks=seq(500,9500,1000))



```
