---
title: "distance_cortex_data_correlation_CSOmap"
author: "Dean de Haas"
date: "26-5-2021"
output: html_document
---

```{r setup, include=FALSE}
library('dplyr')
library('reshape2')
library(ggplot2)
```

import datasets
```{r cars}
#import X and Y positions of mouse brain cortex
original_X_Y_positions <- read.csv("~/stitsch_file.txt", row.names=1, sep="")
colnames(original_X_Y_positions)<-c('ID','X_revised','Y_revised')

#plot the cells
ggplot(original_X_Y_positions,aes(X_revised,Y_revised))+geom_point(size=3)+xlab('X coordinate')+ylab('Y coordinate') +theme(text = element_text(size = 15))


#import X and Y positions calculated by CSOmap
X_Y_positions_calculated_CSOmap<- read.csv("~/x_y_positions_mousy_seqfish.txt", header=FALSE)
ggplot(X_Y_positions_calculated_CSOmap,aes(V1,V2))+geom_point(size=3) +xlab('X coordinate')+ylab('Y coordinate') +theme(text = element_text(size = 15),axis.text.x = element_text( size=15),axis.text.y = element_text( size=15)) +guides(color = guide_legend(override.aes = list(size=5))) 

```

calculate and plot the correlation between true positions and positions calculated by CSOmap of the cells

```{r pressure, echo=FALSE}

distances_between_original_positions<-as.numeric(dist(original_X_Y_positions[,c(2,3)],'euclidean'))
distances_between_original_positions<-as.vector(distances_between_original_positions)


distances_between_positions_calculated_CSOmap<-as.numeric(dist(X_Y_positions_calculated_CSOmap,'euclidean'))


combination_of_all_distances<-data.frame(distances_between_original_positions,distances_between_positions_calculated_CSOmap)
combination_of_all_distances$bin<-cut(combination_of_all_distances$distances_between_original_positions,c(0,500,1000,1500,2000,2500,3000,3500.4000,4500,5000,5500,6000,6500,7000,7500,8000,8500,9000,9500,Inf))
table(combination_of_all_distances$bin)



bin_mean <-aggregate(combination_of_all_distances$distances_between_positions_calculated_CSOmap, list(combination_of_all_distances$bin), function(x) mean = mean(x)) 
bin_sd <-aggregate(combination_of_all_distances$distances_between_positions_calculated_CSOmap, list(combination_of_all_distances$bin), function(x) sd = sd(x))



df<-data.frame(bin_mean,bin_sd$x)
cor.test(combination_of_all_distances$distances_between_original_positions,combination_of_all_distances$distances_between_positions_calculated_CSOmap,method='spearman')
df$Euclidean_distance<-c(seq(500,9500,500))
my_y_title <- expression(paste("CSOmap: ", italic("reconstruction performance")))
ggplot(df,aes(Euclidean_distance,x))+geom_point(size=3)+ggtitle(my_y_title)+geom_errorbar(aes(ymin=as.numeric(x)-as.numeric(bin_sd.x),ymax=as.numeric(x)+as.numeric(bin_sd.x)), width=100,position=position_dodge(.9)) +xlab("Reference spatial Euclidean distance") + ylab("Reconstructed spatial Euclidean distance")+theme(text = element_text(size = 15),axis.text.x = element_text( size=15),axis.text.y = element_text( size=15))+geom_line(size=0.1)+scale_x_continuous(breaks=seq(500,9500,1000))#+scale_x_discrete(breaks=c(seq(0,4000,500)))



```





























