---
title: "novosparc-mouse"
author: "Dean de Haas"
date: "26-5-2021"
output: html_document
---

```{r setup, include=FALSE}
library(dplyr)
library(reshape2)
library(ggplot2)
```

import datasets

```{r cars}

original_positions <- read.csv("~/brain_cortex_true_positions.txt", row.names=1, sep="")
colnames(original_positions)<-c('ID','X_revised','Y_revised')


novosSpaRC_distance_matrix <- read.csv("~/distance_matrix_brain_cortex.csv", row.names=1)

```

assess assumption mouse cortex

```{r pressure, echo=FALSE}

novosSpaRC_distance_matrix<-as.matrix(novosSpaRC_distance_matrix)
novosSpaRC_distance_matrix[upper.tri(novosSpaRC_distance_matrix,diag=T)]<--1000000
# vectorize the matrix 
novosSpaRC_distance_vector <- melt( novosSpaRC_distance_matrix,id.vars=c('from','to'))
#remove the redundant cells from the matrix (e.g. the 0 values that we previously created)
novosSpaRC_distance_vector_minus_redundant_cells<-novosSpaRC_distance_vector[!(novosSpaRC_distance_vector$value==-1000000),]

true_distances<-as.data.frame(as.numeric(dist(original_positions[,c(2,3)])))

novosSpaRC_distance_vector_pearson_distance<-data.frame(novosSpaRC_distance_vector_minus_redundant_cells,true_distances)


novosSpaRC_distance_vector_pearson_distance$bin<-cut(novosSpaRC_distance_vector_pearson_distance$as.numeric.dist.original_positions...c.2..3....,c(0,500,1000,1500,2000,2500,3000,3500.4000,4500,5000,5500,6000,6500,7000,7500,8000,8500,9000,9500,Inf))
bin_mean <-aggregate(novosSpaRC_distance_vector_pearson_distance$value, list(novosSpaRC_distance_vector_pearson_distance$bin), function(x) mean = mean(x)) 
table(novosSpaRC_distance_vector_pearson_distance$bin)
bin_sd <-aggregate(novosSpaRC_distance_vector_pearson_distance$value, list(novosSpaRC_distance_vector_pearson_distance$bin), function(x) sd = sd(x))

bin_mean$distance<-seq(500,9500,500)
cor.test(novosSpaRC_distance_vector_pearson_distance$Var1,as.numeric(novosSpaRC_distance_vector_pearson_distance$Var2),method='spearman')
my_y_title <- expression(paste("novoSpaRc's assumption: ", italic("full gene set")))
ggplot(bin_mean,aes(distance,as.numeric(x)))+geom_point(size=3)+ggtitle(my_y_title)+ geom_errorbar(aes(ymin=as.numeric(x)-as.numeric(bin_sd$x),ymax=as.numeric(x)+as.numeric(bin_sd$x)), width=100,               position=position_dodge(1)) +  xlab("Reference spatial Euclidean distance") + ylab("Expression distance")+scale_y_continuous( breaks=c(0.05,0.1,0.15,0.20,0.25,0.3,0.35,0.4,0.45,0.5,0.55,0.6,0.65,0.7,0.75,0.80,0.85))+theme(text = element_text(size = 15),axis.text.x = element_text( size=15),axis.text.y = element_text( size=15))+scale_x_continuous( breaks=seq(500,9500,1000)) +geom_line(size=0.5)
#View(bin_mean)
```

