---
title: "furhter_develop_simulation_dataset"
author: "Dean de Haas"
date: "12-10-2021"
output: html_document
---


```{r setup, include=FALSE}
library(scater)

```

load datafiles

```{r setup}
simulldata <- read.csv("~/simulldata2.txt", sep="")
simulldata_locs <- read.csv("~/simulldata_locs.txt", sep="")
isolated_genes <- read.csv("~/simulate_data/isolated_genes.txt", sep="")
```

double gene expression dataset

```{r cars}
rev_simulldata<-t(as.matrix(simulldata))
rev_simulldata<-rev(as.data.frame(rev_simulldata))
rev_simulldata<-t(as.matrix(rev_simulldata))
sim_data<-cbind(simulldata,rev_simulldata)
```

assign the different ligand receptor pairs to different groups

```{r pressure, echo=FALSE}
gr1<-c(interaction$isolated_genes.isolated_genes.1.42.[1:21],interaction$isolated_genes.isolated_genes.44.85.[1:21])
gr2<-c(interaction$isolated_genes.isolated_genes.1.42.[22:42],interaction$isolated_genes.isolated_genes.44.85.[22:42])
colnames(sim_data)<-c(gr1,gr2)
sim_data[] <- lapply(sim_data, as.numeric)

```

save new dataset for novoSpaRc analysis

```{r pressure, echo=FALSE}
expression_data<-as.matrix(sim_data)
expression_data<-t(expression_data)
write.table(expression_data,'C:/Users/deand/OneDrive/Documents/simulate_data/novoSpaRc/novosparc_expressions_the422_two_interactionish_groups_spatial_genes.txt',sep = '\t',dec = ",")

```

calculate and save new dataset for CSOmap analysis 

```{r cars}
#Calculate TPM
expression_data_TPM<-calculateTPM(expression_data)
expression_data_TPM<-as.data.frame(expression_data_TPM)
expression_data_TPM[] <- lapply(expression_data_TPM, as.numeric)
write.table(expression_data_TPM,'C:/Users/deand/OneDrive/Documents/CSOmap/data/giotto_422_sim_interactionish/TPM3.txt',sep = '\t',dec = ",")
#save labels as well
label<-as.data.frame(row.names = rownames(simulldata_locs$cells),simulldata_locs$group)
write.table(label,'C:/Users/deand/OneDrive/Documents/CSOmap/data/giotto_422_sim_interactionish/label.txt',sep = '\t',col.names = FALSE)

```
